### ISSUE TITLE
Doesn't support soft memory limition (memory reversation) or docker compose V3

### ISSUE THREAD

**Issue by minzhang28** [micahhausler/container-transform#68]
currently this project only supports docker compose v2 and doesn't tallow us to specify the soft memory limitation. 

suggestion: adding supports to docker compose file v3 resource section, which supports both hard and soft limitation
```
resources:
  limits:
    cpus: '0.001'
    memory: 50M
  reservations:
    cpus: '0.0001'
    memory: 20M
```

**Comment by youcandanch** [comment]
For what it's worth, compose v2 backported memory reservation, which ends up looking like:

```yaml
version: '2'
services:
  memcached:
    image: memcached
    mem_limit: 128m
    mem_reservation: 64m
```
