### ISSUE TITLE
use log volumes awseb-logs-...

### ISSUE THREAD

**Issue by flaushi** [micahhausler/container-transform#96]
Hi,
I'd like to use the log volumes as described here:
https://docs.aws.amazon.com/de_de/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html

I am converting a docker-compose.yml, but don't know how to get such a `awseb-logs-` volume. 

if I use such a docker-compose:
``` 
version: '2'

services:
    
    php:
        image: php:latest
        mem_limit: 950m
        restart: always
        links:
            - redis
            - db
        volumes:
            - awseb-logs-mylog:/var/log
```
it'll give me
```
{
            "essential": true,
            "image": "php:latest",
            "links": [
                "redis",
                "db"
            ],
            "memory": 950,
            "mountPoints": [
                {
                    "containerPath": "/var/log",
                    "sourceVolume": "Awseb-Logs-mylog"
                }
            ],
            "name": "php"
        },
