### ISSUE TITLE
Container web is missing required parameter "image".

### ISSUE THREAD

**Issue by ghost** [micahhausler/container-transform#98]
I want to convert Docker compose file to JSON file by using:
`cat docker-compose.prod.yml | container-transform  -v` command.
For the services with the image parameter is works, but for the services with build parameter gives this error. 

Successful:
```
db:
        image: postgres
```

Failed:
```
 db:
        build: 
            context: .
            dockerfile: Dockerfile
```

How can I solve this problem?
